"""Electrification, iron: 4 electric drills -> stone furnaces. Long-handed
inserters fuel the furnaces from a coal belt (row 49) fed by an electric drill
on the coal field; inserters move plates onto a belt (row 48) that runs into
the iron chest from its south side. Resumable.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import fx  # noqa: E402
from bridge import Bridge  # noqa: E402
from play import ChatInterrupt, PlayFail, gather, inv, must, run  # noqa: E402
from power_run import clear_trees, tag_state  # noqa: E402
from scale_run import top_up  # noqa: E402
from science_run import COPPER_CHEST, IRON_CHEST, shot_all  # noqa: E402

TAG = "elec-iron"
UNITS = [-85, -82, -79, -76]   # left column of each drill
COAL_DRILL = (-103, 46)        # top-left; outputs south onto (-102, 49)
X0, Y0 = -103, 42


def layout():
    g = {}
    for X in UNITS:
        for dx in range(3):
            for dy in range(3):
                g[(X + dx, 42 + dy)] = "Mv"
        for dx in (1, 2):
            for dy in (45, 46):
                g[(X + dx, dy)] = "F."
        g[(X, 46)] = "p."
        g[(X + 1, 47)] = "J^"   # coal belt (row 49) -> furnace (row 45)
        g[(X + 2, 47)] = "Iv"   # furnace -> plate belt (row 48)
    for dx in range(3):
        for dy in range(3):
            g[(COAL_DRILL[0] + dx, COAL_DRILL[1] + dy)] = "Mv"
    # plate belt: west along row 48, then north up x=-91 into the chest
    for x in range(-90, -73):
        g[(x, 48)] = "b<"
    for y in range(44, 49):
        g[(-91, y)] = "b^"
    g[(-91, 43)] = "e^"
    g[(-91, 42)] = "I^"         # belt end -> iron chest (-91, 41)
    # coal belt: east along row 49 from under the coal drill
    for x in range(-102, -74):
        g[(x, 49)] = "b>"
    g[(-74, 49)] = "e>"
    for p in [(-90, 43), (-94, 45), (-100, 45)]:
        g[p] = "p."
    return g


def write_stamp():
    g = layout()
    x1, y1 = max(x for x, _ in g), max(y for _, y in g)
    rows = ["# Generated by client/elec_iron_run.py: electric iron mining + smelting.",
            "# Laid out in world tiles; plan it at %d %d rotation 0." % (X0, Y0)]
    for y in range(Y0, y1 + 1):
        rows.append("".join(g.get((x, y), "..") for x in range(X0, x1 + 1)))
    with open(os.path.join(fx.ROOT, "stamps", "elec-iron.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(rows) + "\n")
    return [X0, Y0, x1, y1]


def materials(b):
    need = {"electric-mining-drill": 5, "stone-furnace": 4, "long-handed-inserter": 4, "inserter": 5, "transport-belt": 52}
    short = {k: max(0, n - inv(b).get(k, 0)) for k, n in need.items()}
    ins_total = short["inserter"] + short["long-handed-inserter"]
    circuits = max(0, 3 * short["electric-mining-drill"] + ins_total - inv(b).get("electronic-circuit", 0))
    belt_crafts = (short["transport-belt"] + 1) // 2
    gears = max(0, 5 * short["electric-mining-drill"] + ins_total + short["long-handed-inserter"] + belt_crafts
                - inv(b).get("iron-gear-wheel", 0))
    iron = (2 * gears + circuits + 10 * short["electric-mining-drill"] + ins_total + short["long-handed-inserter"]
            + belt_crafts + 5)
    top_up(b, *IRON_CHEST, "iron-plate", iron)
    top_up(b, *COPPER_CHEST, "copper-plate", (3 * circuits + 1) // 2)
    if short["stone-furnace"]:
        gather(b, "stone", 5 * short["stone-furnace"])
    if circuits:
        must("craft", "copper-cable", (3 * circuits + 1) // 2)
        must("craft", "electronic-circuit", circuits)
    if gears:
        must("craft", "iron-gear-wheel", gears)
    if belt_crafts:
        must("craft", "transport-belt", belt_crafts)
    for k in ("electric-mining-drill", "stone-furnace", "inserter", "long-handed-inserter"):
        if short[k]:
            must("craft", k, short[k])


def plates_in_chest(b):
    s = b.call("scan", {"area": [-91, 41, -91, 41]})
    return sum((e.get("contents") or {}).get("iron-plate", 0) for e in s["entities"])


def main():
    with Bridge() as b:
        must("spawn")
        bbox = write_stamp()
        state = tag_state(b, TAG)
        if state != "built":
            materials(b)
        if state is None:
            must("walk", -88, 50, "--radius", 3)
            clear_trees(b, bbox)
            must("plan", "elec-iron", X0, Y0, 0, "--tag", TAG)
            state = "ghost"
        if state == "ghost":
            x1, y1, x2, y2 = bbox
            must("look", x1 - 1, y1 - 1, x2 + 1, y2 + 1)
            shot_all(bbox)
            if run("lint", TAG) != 0:
                raise PlayFail("elec-iron failed lint")
            must("build", TAG)
        code = run("prove", TAG, 3600)
        if code:
            raise PlayFail("prove failed")
        must("say", "Electric iron is running: 4 electric drills into furnaces, coal by belt, plates into the iron chest.")
        print("ELEC IRON PASS")


if __name__ == "__main__":
    try:
        main()
    except ChatInterrupt as e:
        print(f"INTERRUPTED: {e}")
        sys.exit(3)
    except PlayFail as e:
        print(f"FAIL: {e}", file=sys.stderr)
        sys.exit(1)
