"""Green science (logistic-science-pack), first assembler.

elec-iron2: a mirror of elec-iron on rows 50..56 that shares its coal belt
(row 49, extended east). Its plates run east on row 50, north up x=-57, then
west along row 30 (belt M). Lanes: iron arrives on M's south lane; a gear
assembler south of M drops gears onto M's north lane.

green: copper cable (K) -> circuit (C) -> inserter assembler (N) -> green
assembler (G) <- belt assembler (Bt). G sits under lab 1 (-68..-66, 22..24)
and feeds it; lab 1 already gets red. K takes copper from the red copper/gear
belt (row 20), extended east. C, N, Bt take iron (+gears) from M.
Resumable.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import fx  # noqa: E402
from bridge import Bridge  # noqa: E402
from play import ChatInterrupt, PlayFail, gather, inv, must, run  # noqa: E402
from power_run import clear_trees, tag_state  # noqa: E402
from scale_run import top_up  # noqa: E402
from science_run import COPPER_CHEST, IRON_CHEST, finished, shot_all  # noqa: E402

IRON_UNITS = [-79, -76, -73, -70]


def asm(g, x, y, key):
    for dx in range(3):
        for dy in range(3):
            g[(x + dx, y + dy)] = "A" + key


def layout_iron2():
    g = {}
    for X in IRON_UNITS:
        for dx in range(3):
            for dy in range(3):
                g[(X + dx, 54 + dy)] = "M^"
        for dx in (1, 2):
            for dy in (52, 53):
                g[(X + dx, dy)] = "F."
        g[(X, 52)] = "p."
        g[(X + 1, 51)] = "Jv"   # coal belt (row 49) -> furnace (row 53)
        g[(X + 2, 51)] = "I^"   # furnace (row 52) -> plate belt (row 50)
    for x in range(-73, -67):
        g[(x, 49)] = "b>"       # coal belt extension
    g[(-67, 49)] = "e>"
    for x in range(-77, -57):
        g[(x, 50)] = "b>"
    for y in range(31, 51):
        g[(-57, y)] = "b^"
    g[(-57, 30)] = "b<"
    for x in range(-71, -57):
        g[(x, 30)] = "b<"
    g[(-72, 30)] = "e<"
    return g


def layout_green():
    """South of belt M. M (row 30, west) loops down x=-73 and back east on row 40,
    so both assembler rows reach iron + copper. Copper joins M's north lane from
    a filtered inserter on the red copper/gear belt, down x=-63, under the coal
    belt and the M belt's row-29 neighbourhood by underground, sideloading at
    (-63,30). Green flasks go north up x=-67 under rows 28..30 into lab 1."""
    g = {}
    # copper: filtered inserter takes copper (not gears) off the red belt's end
    g[(-70, 20)] = "I>"
    for x in range(-69, -63):
        g[(x, 20)] = "b>"
    g[(-63, 20)] = "bv"
    for y in range(21, 27):
        g[(-63, y)] = "bv"
    g[(-63, 27)] = "uv"
    g[(-63, 29)] = "Wv"        # sideloads into M (-63, 30): north lane
    # M loop
    g[(-73, 30)] = "bv"
    for y in range(31, 40):
        g[(-73, y)] = "bv"
    g[(-73, 40)] = "b>"
    for x in range(-72, -59):
        g[(x, 40)] = "b>"
    g[(-59, 40)] = "e>"        # stop short of the M column at x=-57
    # row 1 (rows 32-34) from M via row 31; row 2 (rows 36-38) from row 40 via row 39
    asm(g, -72, 32, "g")       # Gb: gears for the belt assembler
    asm(g, -64, 32, "h")       # Ga: gears for the inserter assembler
    asm(g, -60, 32, "k")       # K: copper cable
    asm(g, -72, 36, "t")       # Bt: belts
    asm(g, -68, 36, "l")       # G: green flasks
    asm(g, -64, 36, "n")       # N: inserters
    asm(g, -60, 36, "c")       # C: circuits
    for x in (-71, -63, -59):
        g[(x, 31)] = "Iv"      # M -> row 1
        g[(x, 39)] = "I^"      # row-40 belt -> row 2
    g[(-71, 35)] = "Iv"        # Gb -> Bt
    g[(-63, 35)] = "Iv"        # Ga -> N
    g[(-59, 35)] = "Iv"        # K -> C
    g[(-69, 37)] = "I>"        # Bt -> G
    g[(-65, 37)] = "I<"        # N -> G
    g[(-61, 37)] = "I<"        # C -> N
    # green flasks: G -> belt up x=-67, under rows 28..30, into lab 1
    g[(-67, 35)] = "I^"
    for y in (32, 33, 34):
        g[(-67, y)] = "b^"
    g[(-67, 31)] = "u^"
    g[(-67, 27)] = "U^"
    g[(-67, 26)] = "e^"
    g[(-67, 25)] = "I^"
    for p in [(-69, 33), (-65, 33), (-61, 33), (-69, 39), (-65, 39), (-61, 39), (-66, 25)]:
        g[p] = "p."
    return g


KEYS = ["@l logistic-science-pack", "@n inserter", "@t transport-belt", "@c electronic-circuit",
        "@k copper-cable", "@g iron-gear-wheel", "@h iron-gear-wheel"]


def write_stamp(name, g, keys=()):
    x0, y0 = min(x for x, _ in g), min(y for _, y in g)
    x1, y1 = max(x for x, _ in g), max(y for _, y in g)
    rows = [f"# Generated by client/green_run.py. Laid out in world tiles; plan it at {x0} {y0} rotation 0.", *keys]
    for y in range(y0, y1 + 1):
        rows.append("".join(g.get((x, y), "..") for x in range(x0, x1 + 1)))
    with open(os.path.join(fx.ROOT, "stamps", name + ".txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(rows) + "\n")
    return [x0, y0, x1, y1]


def count(g, code):
    """How many entities of a stamp code (multi-tile entities counted once)."""
    tiles = sum(1 for v in g.values() if v[0] == code)
    return tiles // {"A": 9, "M": 9, "F": 4, "L": 9}.get(code, 1)


def materials(b, g):
    need = {"electric-mining-drill": count(g, "M"), "stone-furnace": count(g, "F"),
            "long-handed-inserter": count(g, "J"), "inserter": count(g, "I"),
            "assembling-machine-1": count(g, "A"), "transport-belt": count(g, "b") + count(g, "e"),
            "underground-belt": count(g, "u") + count(g, "U") + count(g, "W"),
            "small-electric-pole": count(g, "p"), "lab": count(g, "L")}
    short = {k: max(0, n - inv(b).get(k, 0)) for k, n in need.items()}
    ins_crafts = short["inserter"] + short["long-handed-inserter"]
    short["transport-belt"] += 4 * short["lab"]
    circuits = max(0, 3 * short["electric-mining-drill"] + 3 * short["assembling-machine-1"] + 10 * short["lab"] + ins_crafts
                   - inv(b).get("electronic-circuit", 0))
    ug = (short.get("underground-belt", 0) + 1) // 2
    belt_crafts = (short["transport-belt"] + 5 * ug + 1) // 2
    gears = max(0, 5 * short["electric-mining-drill"] + 5 * short["assembling-machine-1"] + 10 * short["lab"] + ins_crafts
                + short["long-handed-inserter"] + belt_crafts - inv(b).get("iron-gear-wheel", 0))
    iron = (2 * gears + circuits + 10 * short["electric-mining-drill"] + 9 * short["assembling-machine-1"]
            + ins_crafts + short["long-handed-inserter"] + belt_crafts + 10 * ug + 5)
    top_up(b, *IRON_CHEST, "iron-plate", iron)
    top_up(b, *COPPER_CHEST, "copper-plate", (3 * circuits + 1) // 2 + 1)
    if short["stone-furnace"]:
        gather(b, "stone", 5 * short["stone-furnace"])
    if short["small-electric-pole"]:
        raise PlayFail(f"need {short['small-electric-pole']} more small poles")
    if circuits:
        must("craft", "copper-cable", (3 * circuits + 1) // 2)
        must("craft", "electronic-circuit", circuits)
    if gears:
        must("craft", "iron-gear-wheel", gears)
    if belt_crafts:
        must("craft", "transport-belt", belt_crafts)
    if short.get("underground-belt"):
        # 10 iron + 5 belts -> 2 undergrounds
        must("craft", "underground-belt", (short["underground-belt"] + 1) // 2)
    for k in ("electric-mining-drill", "stone-furnace", "inserter", "long-handed-inserter", "assembling-machine-1", "lab"):
        if short[k]:
            must("craft", k, short[k])


def place(b, tag, g, keys=(), walk=None):
    bbox = write_stamp(tag, g, keys)
    state = tag_state(b, tag)
    if state == "built":
        return bbox
    materials(b, g)
    if state is None and tag == "green":
        clear_dead_pole(b)
    if state is None:
        must("walk", *(walk or ((bbox[0] + bbox[2]) / 2, bbox[3] + 2)), "--radius", 3)
        clear_trees(b, bbox)
        must("plan", tag, bbox[0], bbox[1], 0, "--tag", tag)
    x1, y1, x2, y2 = bbox
    must("look", x1 - 1, y1 - 1, x2 + 1, y2 + 1)
    shot_all(bbox)
    if run("lint", tag) != 0:
        raise PlayFail(f"{tag} failed lint")
    must("build", tag)
    return bbox


def clear_dead_pole(b):
    """The player's pole at (-62,34) only links to (-65,29) and powers nothing;
    it sits in the inserter-gear assembler's slot."""
    s = b.call("scan", {"area": [-62, 34, -62, 34]})
    if any(e["name"] == "small-electric-pole" for e in s["entities"]):
        must("walk", -61.5, 36, "--radius", 2)
        must("mine", -61.5, 34.5)
        must("say", "I picked up your spare pole at (-62,34); it was a dead end and sat where an assembler goes.")


def set_copper_filter(b):
    out = b.lua("local e = game.surfaces[1].find_entity('inserter', {-69.5, 20.5})"
                " if e then e.use_filters = true e.set_filter(1, 'copper-plate') rcon.print(tostring(e.get_filter(1).name)) else rcon.print('none') end")
    print("copper filter:", out.strip())
    if "copper-plate" not in out:
        raise PlayFail("could not set the copper filter")


def main():
    with Bridge() as b:
        must("spawn")
        place(b, "elec-iron2", layout_iron2())
        place(b, "green", layout_green(), KEYS)
        set_copper_filter(b)
        # belts take a while to fill: warm up before judging
        b.run_ticks(3600)
        if run("prove", "elec-iron2", 1800):
            raise PlayFail("elec-iron2 prove failed")
        ents = fx.tag_entities(b, "green")
        gpos = next(e["position"] for e in ents if e["name"] == "assembling-machine-1" and e["tile"] == [-68, 26])
        before = finished(b, *gpos)
        code = run("prove", "green", 3600)
        after = finished(b, *gpos)
        print(f"green flasks made {before} -> {after}")
        if code:
            raise PlayFail("green prove failed")
        if after <= before:
            raise PlayFail("the green assembler made nothing")
        must("say", "Green science is running into lab 1!")
        print("GREEN RUN PASS")


if __name__ == "__main__":
    try:
        main()
    except ChatInterrupt as e:
        print(f"INTERRUPTED: {e}")
        sys.exit(3)
    except PlayFail as e:
        print(f"FAIL: {e}", file=sys.stderr)
        sys.exit(1)
