"""Green science (logistic-science-pack), first assembler.

elec-iron2: a mirror of elec-iron on rows 50..56 that shares its coal belt
(row 49, extended east). Its plates run east on row 50, north up x=-57, then
west along row 30 (belt M). Lanes: iron arrives on M's south lane; a gear
assembler south of M drops gears onto M's north lane.

green: copper cable (K) -> circuit (C) -> inserter assembler (N) -> green
assembler (G) <- belt assembler (Bt). G sits under lab 1 (-68..-66, 22..24)
and feeds it; lab 1 already gets red. K takes copper from the red copper/gear
belt (row 20), extended east. C, N, Bt take iron (+gears) from M.
Resumable.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import fx  # noqa: E402
from bridge import Bridge  # noqa: E402
from play import ChatInterrupt, PlayFail, gather, inv, must, run  # noqa: E402
from power_run import clear_trees, tag_state  # noqa: E402
from scale_run import top_up  # noqa: E402
from science_run import COPPER_CHEST, IRON_CHEST, finished, shot_all  # noqa: E402

IRON_UNITS = [-79, -76, -73, -70]


def asm(g, x, y, key):
    for dx in range(3):
        for dy in range(3):
            g[(x + dx, y + dy)] = "A" + key


def layout_iron2():
    g = {}
    for X in IRON_UNITS:
        for dx in range(3):
            for dy in range(3):
                g[(X + dx, 54 + dy)] = "M^"
        for dx in (1, 2):
            for dy in (52, 53):
                g[(X + dx, dy)] = "F."
        g[(X, 52)] = "p."
        g[(X + 1, 51)] = "Jv"   # coal belt (row 49) -> furnace (row 53)
        g[(X + 2, 51)] = "I^"   # furnace (row 52) -> plate belt (row 50)
    for x in range(-73, -67):
        g[(x, 49)] = "b>"       # coal belt extension
    g[(-67, 49)] = "e>"
    for x in range(-77, -57):
        g[(x, 50)] = "b>"
    for y in range(31, 51):
        g[(-57, y)] = "b^"
    g[(-57, 30)] = "b<"
    for x in range(-71, -57):
        g[(x, 30)] = "b<"
    g[(-72, 30)] = "e<"
    return g


def layout_green():
    g = {}
    asm(g, -68, 26, "l")        # G: green flasks
    asm(g, -64, 26, "n")        # N: inserters
    asm(g, -72, 26, "t")        # Bt: belts
    asm(g, -60, 26, "c")        # C: circuits
    asm(g, -60, 22, "k")        # K: copper cable
    asm(g, -62, 32, "g")        # Gm: gears onto M
    g[(-67, 25)] = "I^"         # G -> lab 1
    g[(-65, 27)] = "I<"         # N -> G
    g[(-69, 27)] = "I>"         # Bt -> G
    g[(-61, 27)] = "I<"         # C -> N
    g[(-59, 25)] = "Iv"         # K -> C
    g[(-59, 21)] = "Iv"         # copper belt end -> K
    for x in (-59, -63, -71):
        g[(x, 29)] = "I^"       # M -> C, N, Bt
    g[(-61, 31)] = "Iv"         # M -> gear assembler
    g[(-60, 31)] = "I^"         # gear assembler -> M (north lane)
    for x in range(-70, -59):
        g[(x, 20)] = "b>"       # copper/gear belt extension
    g[(-59, 20)] = "e>"
    for p in [(-69, 29), (-65, 25), (-61, 25), (-61, 21), (-61, 29)]:
        g[p] = "p."
    return g


KEYS = ["@l logistic-science-pack", "@n inserter", "@t transport-belt", "@c electronic-circuit",
        "@k copper-cable", "@g iron-gear-wheel"]


def write_stamp(name, g, keys=()):
    x0, y0 = min(x for x, _ in g), min(y for _, y in g)
    x1, y1 = max(x for x, _ in g), max(y for _, y in g)
    rows = [f"# Generated by client/green_run.py. Laid out in world tiles; plan it at {x0} {y0} rotation 0.", *keys]
    for y in range(y0, y1 + 1):
        rows.append("".join(g.get((x, y), "..") for x in range(x0, x1 + 1)))
    with open(os.path.join(fx.ROOT, "stamps", name + ".txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(rows) + "\n")
    return [x0, y0, x1, y1]


def count(g, code):
    """How many entities of a stamp code (multi-tile entities counted once)."""
    tiles = sum(1 for v in g.values() if v[0] == code)
    return tiles // {"A": 9, "M": 9, "F": 4}.get(code, 1)


def materials(b, g):
    need = {"electric-mining-drill": count(g, "M"), "stone-furnace": count(g, "F"),
            "long-handed-inserter": count(g, "J"), "inserter": count(g, "I"),
            "assembling-machine-1": count(g, "A"), "transport-belt": count(g, "b") + count(g, "e"),
            "small-electric-pole": count(g, "p")}
    short = {k: max(0, n - inv(b).get(k, 0)) for k, n in need.items()}
    ins_crafts = short["inserter"] + short["long-handed-inserter"]
    circuits = max(0, 3 * short["electric-mining-drill"] + 3 * short["assembling-machine-1"] + ins_crafts
                   - inv(b).get("electronic-circuit", 0))
    belt_crafts = (short["transport-belt"] + 1) // 2
    gears = max(0, 5 * short["electric-mining-drill"] + 5 * short["assembling-machine-1"] + ins_crafts
                + short["long-handed-inserter"] + belt_crafts - inv(b).get("iron-gear-wheel", 0))
    iron = (2 * gears + circuits + 10 * short["electric-mining-drill"] + 9 * short["assembling-machine-1"]
            + ins_crafts + short["long-handed-inserter"] + belt_crafts + 5)
    top_up(b, *IRON_CHEST, "iron-plate", iron)
    top_up(b, *COPPER_CHEST, "copper-plate", (3 * circuits + 1) // 2 + 1)
    if short["stone-furnace"]:
        gather(b, "stone", 5 * short["stone-furnace"])
    if short["small-electric-pole"]:
        raise PlayFail(f"need {short['small-electric-pole']} more small poles")
    if circuits:
        must("craft", "copper-cable", (3 * circuits + 1) // 2)
        must("craft", "electronic-circuit", circuits)
    if gears:
        must("craft", "iron-gear-wheel", gears)
    if belt_crafts:
        must("craft", "transport-belt", belt_crafts)
    for k in ("electric-mining-drill", "stone-furnace", "inserter", "long-handed-inserter", "assembling-machine-1"):
        if short[k]:
            must("craft", k, short[k])


def place(b, tag, g, keys=(), walk=None):
    bbox = write_stamp(tag, g, keys)
    state = tag_state(b, tag)
    if state == "built":
        return bbox
    materials(b, g)
    if state is None:
        must("walk", *(walk or ((bbox[0] + bbox[2]) / 2, bbox[3] + 2)), "--radius", 3)
        clear_trees(b, bbox)
        must("plan", tag, bbox[0], bbox[1], 0, "--tag", tag)
    x1, y1, x2, y2 = bbox
    must("look", x1 - 1, y1 - 1, x2 + 1, y2 + 1)
    shot_all(bbox)
    if run("lint", tag) != 0:
        raise PlayFail(f"{tag} failed lint")
    must("build", tag)
    return bbox


def main():
    with Bridge() as b:
        must("spawn")
        place(b, "elec-iron2", layout_iron2())
        place(b, "green", layout_green(), KEYS)
        # belts take a while to fill: warm up before judging
        b.run_ticks(3600)
        if run("prove", "elec-iron2", 1800):
            raise PlayFail("elec-iron2 prove failed")
        ents = fx.tag_entities(b, "green")
        gpos = next(e["position"] for e in ents if e["name"] == "assembling-machine-1" and e["tile"] == [-68, 26])
        before = finished(b, *gpos)
        code = run("prove", "green", 3600)
        after = finished(b, *gpos)
        print(f"green flasks made {before} -> {after}")
        if code:
            raise PlayFail("green prove failed")
        if after <= before:
            raise PlayFail("the green assembler made nothing")
        must("say", "Green science is running into lab 1!")
        print("GREEN RUN PASS")


if __name__ == "__main__":
    try:
        main()
    except ChatInterrupt as e:
        print(f"INTERRUPTED: {e}")
        sys.exit(3)
    except PlayFail as e:
        print(f"FAIL: {e}", file=sys.stderr)
        sys.exit(1)
