"""Scale red science to 3 flask assemblers. The gear assembler from task 16 also
drops gears onto the copper belt (north lane; copper rides the south lane), and
two more flask assemblers north of that belt take copper + gears from it, each
feeding its own lab. Resumable.
"""
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import fx  # noqa: E402
from bridge import Bridge  # noqa: E402
from play import ChatInterrupt, PlayFail, inv, must, run, withdraw  # noqa: E402
from power_run import clear_trees, tag_state  # noqa: E402
from science_run import COPPER_CHEST, IRON_CHEST, finished, shot_all  # noqa: E402

TAG = "science2"
X0, Y0 = -76, 12


def layout():
    g = {}
    for x in range(3):
        for y in range(3):
            g[(-76 + x, 12 + y)] = "L."   # lab A
            g[(-72 + x, 12 + y)] = "L."   # lab B
            g[(-76 + x, 16 + y)] = "Ar"   # flask assembler A
            g[(-72 + x, 16 + y)] = "Ar"   # flask assembler B
    g[(-75, 15)] = "I^"   # A -> lab A
    g[(-71, 15)] = "I^"   # B -> lab B
    g[(-75, 19)] = "I^"   # copper belt -> A
    g[(-71, 19)] = "I^"   # copper belt end -> B
    g[(-75, 21)] = "I^"   # gear assembler -> copper belt
    g[(-73, 17)] = "p."
    g[(-73, 13)] = "p."
    return g


def write_stamp():
    g = layout()
    x1, y1 = max(x for x, _ in g), max(y for _, y in g)
    rows = ["# Generated by client/scale_run.py: red-science lines 2 and 3 (north of the copper belt).",
            "# Laid out in world tiles; plan it at %d %d rotation 0." % (X0, Y0),
            "@r automation-science-pack"]
    for y in range(Y0, y1 + 1):
        rows.append("".join(g.get((x, y), "..") for x in range(X0, x1 + 1)))
    with open(os.path.join(fx.ROOT, "stamps", "science2.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(rows) + "\n")
    return [X0, Y0, x1, y1]


def top_up(b, x, y, item, want):
    """Take from a smelter chest until we hold `want`, waiting for the smelter if it runs dry."""
    deadline = time.time() + 900
    while inv(b).get(item, 0) < want:
        got = withdraw(b, x, y, item, want - inv(b).get(item, 0))
        if inv(b).get(item, 0) >= want:
            return
        if time.time() > deadline:
            raise PlayFail(f"{item} chest stayed empty for 15 min")
        print(f"waiting for {item}: have {inv(b).get(item, 0)}/{want} (took {got})", flush=True)
        b.run_ticks(1800)


def materials(b):
    need = {"lab": 2, "assembling-machine-1": 2, "inserter": 5}
    short = {k: max(0, n - inv(b).get(k, 0)) for k, n in need.items()}
    circuits = 10 * short["lab"] + 3 * short["assembling-machine-1"] + short["inserter"] - inv(b).get("electronic-circuit", 0)
    belts = 4 * short["lab"] - inv(b).get("transport-belt", 0)
    belt_crafts = max(0, (belts + 1) // 2)
    gears = 10 * short["lab"] + 5 * short["assembling-machine-1"] + short["inserter"] + belt_crafts - inv(b).get("iron-gear-wheel", 0)
    copper = max(0, (3 * max(circuits, 0) + 1) // 2)
    iron = 2 * max(gears, 0) + max(circuits, 0) + 9 * short["assembling-machine-1"] + short["inserter"] + belt_crafts + 10
    top_up(b, *IRON_CHEST, "iron-plate", iron)
    top_up(b, *COPPER_CHEST, "copper-plate", copper)
    if circuits > 0:
        must("craft", "copper-cable", (3 * circuits + 1) // 2)
        must("craft", "electronic-circuit", circuits)
    if gears > 0:
        must("craft", "iron-gear-wheel", gears)
    if belt_crafts:
        must("craft", "transport-belt", belt_crafts)
    for k in ("lab", "assembling-machine-1", "inserter"):
        if short[k]:
            must("craft", k, short[k])


def main():
    with Bridge() as b:
        must("spawn")
        bbox = write_stamp()
        state = tag_state(b, TAG)
        if state != "built":
            materials(b)
        if state is None:
            must("walk", -73, 21, "--radius", 3)
            clear_trees(b, bbox)
            must("plan", "science2", X0, Y0, 0, "--tag", TAG)
            state = "ghost"
        if state == "ghost":
            x1, y1, x2, y2 = bbox
            must("look", x1 - 1, y1 - 1, x2 + 1, y2 + 3)
            shot_all([x1, y1, x2, y2 + 2])
            if run("lint", TAG) != 0:
                raise PlayFail("science2 failed lint")
            must("build", TAG)
        asms = [e for e in fx.tag_entities(b, TAG) if e["name"] == "assembling-machine-1"]
        before = [finished(b, *e["position"]) for e in asms]
        before_p = b.call("tech").get("progress") or 0
        code = run("prove", TAG, 3600)
        after = [finished(b, *e["position"]) for e in asms]
        tech = b.call("tech")
        print(f"flasks made {before} -> {after}; {tech.get('current')} {before_p:.2f} -> {(tech.get('progress') or 0):.2f}")
        if code:
            raise PlayFail("prove failed")
        if any(a <= c for a, c in zip(after, before)):
            raise PlayFail("a flask assembler made nothing")
        must("say", "3 red-science assemblers and 3 labs are running.")
        print("SCALE RUN PASS")


if __name__ == "__main__":
    try:
        main()
    except ChatInterrupt as e:
        print(f"INTERRUPTED: {e}")
        sys.exit(3)
    except PlayFail as e:
        print(f"FAIL: {e}", file=sys.stderr)
        sys.exit(1)
