"""Task 16: automated red science. Iron plates leave the e2e smelter chest on a
belt to a gear assembler; copper leaves the copper smelter chest on a belt to
the red-flask assembler; gears and flasks move by inserter; flasks go into the
lab built in task 15. Electric inserters, powered from the lab's pole.
Fair play throughout; resumable (each step checks the tag).
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import fx  # noqa: E402
from bridge import Bridge  # noqa: E402
from play import ChatInterrupt, PlayFail, inv, must, run, withdraw  # noqa: E402
from power_run import clear_trees, tag_state  # noqa: E402

TAG = "science"
IRON_CHEST = (-90.5, 41.5)    # tile (-91,41)
COPPER_CHEST = (-77.5, 10.5)  # tile (-78,10)
X0, Y0 = -91, 11              # stamp top-left; the stamp is laid out in world tiles
NEXT_RESEARCH = ["logistics", "electric-mining-drill"]


def layout():
    """World tile -> 2-char stamp code."""
    g = {}
    # iron: inserter out of the chest's north side, belt north to y=26, then east
    g[(-91, 40)] = "I^"
    for y in range(27, 40):
        g[(-91, y)] = "b^"
    for x in range(-91, -75):
        g[(x, 26)] = "b>"
    g[(-75, 26)] = "e>"
    g[(-75, 25)] = "I^"             # belt end -> gear assembler
    # copper: inserter out of the chest's south side, belt south to y=20, then east
    g[(-78, 11)] = "Iv"
    for y in range(12, 20):
        g[(-78, y)] = "bv"
    for x in range(-78, -71):
        g[(x, 20)] = "b>"
    g[(-71, 20)] = "e>"
    g[(-71, 21)] = "Iv"             # belt end -> flask assembler
    for x in range(3):
        for y in range(3):
            g[(-76 + x, 22 + y)] = "Ag"
            g[(-72 + x, 22 + y)] = "Ar"
    g[(-73, 23)] = "I>"             # gears -> flask assembler
    g[(-69, 23)] = "I>"             # flasks -> lab (tiles -68..-66)
    for p in [(-69, 22), (-73, 21), (-77, 25), (-84, 27), (-89, 31), (-90, 38), (-77, 16), (-77, 12)]:
        g[p] = "p."
    return g


def write_stamp():
    g = layout()
    x1, y1 = max(x for x, _ in g), max(y for _, y in g)
    rows = ["# Generated by client/science_run.py: red science between the smelters and the lab.",
            "# Laid out in world tiles; plan it at %d %d rotation 0." % (X0, Y0),
            "@g iron-gear-wheel", "@r automation-science-pack"]
    for y in range(Y0, y1 + 1):
        rows.append("".join(g.get((x, y), "..") for x in range(X0, x1 + 1)))
    with open(os.path.join(fx.ROOT, "stamps", "science.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(rows) + "\n")
    return [X0, Y0, x1, y1]


def materials(b):
    # 46 belts (23 crafts), 2 assemblers, 6 inserters, 8 poles
    if inv(b).get("iron-plate", 0) < 150:
        withdraw(b, *IRON_CHEST, "iron-plate", 150 - inv(b).get("iron-plate", 0))
    if inv(b).get("copper-plate", 0) < 20:
        withdraw(b, *COPPER_CHEST, "copper-plate", 20 - inv(b).get("copper-plate", 0))
    need = {"transport-belt": 46, "assembling-machine-1": 2, "inserter": 6}
    short = {k: max(0, n - inv(b).get(k, 0)) for k, n in need.items()}
    circuits = 3 * short["assembling-machine-1"] + short["inserter"] - inv(b).get("electronic-circuit", 0)
    if circuits > 0:
        must("craft", "copper-cable", (3 * circuits + 1) // 2)
        must("craft", "electronic-circuit", circuits)
    gears = (short["transport-belt"] + 1) // 2 + 5 * short["assembling-machine-1"] + short["inserter"]
    gears -= inv(b).get("iron-gear-wheel", 0)
    if gears > 0:
        must("craft", "iron-gear-wheel", gears)
    if short["transport-belt"]:
        must("craft", "transport-belt", (short["transport-belt"] + 1) // 2)
    for k in ("assembling-machine-1", "inserter"):
        if short[k]:
            must("craft", k, short[k])


def shot_all(bbox):
    x1, y1, x2, y2 = bbox
    w_t, h_t = x2 - x1 + 6, y2 - y1 + 6
    zoom = round(min(1.0, 3840 / (32 * w_t), 2160 / (32 * h_t)), 3)
    must("shot", (x1 + x2 + 1) / 2, (y1 + y2 + 1) / 2, zoom,
         "--w", int(w_t * 32 * zoom) + 1, "--h", int(h_t * 32 * zoom) + 1)


def finished(b, x, y):
    out = b.lua("local e = game.surfaces[1].find_entities_filtered{name='assembling-machine-1', position={%s,%s}}[1]"
                " rcon.print(e and e.products_finished or -1)" % (x, y)).strip()
    return int(out)


def main():
    with Bridge() as b:
        must("spawn")
        bbox = write_stamp()
        materials(b)
        state = tag_state(b, TAG)
        if state is None:
            must("walk", -80, 24, "--radius", 3)
            clear_trees(b, bbox)
            must("plan", "science", X0, Y0, 0, "--tag", TAG)
            state = "ghost"
        if state == "ghost":
            x1, y1, x2, y2 = bbox
            must("look", x1 - 1, y1 - 1, x2 + 1, y2 + 1)
            shot_all(bbox)
            if run("lint", TAG) != 0:
                raise PlayFail("science line failed lint")
            must("build", TAG)
        ents = fx.tag_entities(b, TAG)
        flask = next(e for e in ents if e["name"] == "assembling-machine-1" and e.get("recipe") != "iron-gear-wheel"
                     and e["tile"][0] == -72)
        cur = b.call("tech").get("current")
        if not cur:
            for t in NEXT_RESEARCH:
                if run("research", t) == 0:
                    break
        before_n = finished(b, *flask["position"])
        before_p = b.call("tech").get("progress") or 0
        code = run("prove", TAG, 3600)
        after_n = finished(b, *flask["position"])
        tech = b.call("tech")
        print(f"red flasks made {before_n} -> {after_n}; {tech.get('current')} {before_p:.2f} -> {(tech.get('progress') or 0):.2f}")
        if code:
            raise PlayFail("prove failed")
        if after_n <= before_n:
            raise PlayFail("the flask assembler made nothing")
        if (tech.get("progress") or 0) <= before_p:
            raise PlayFail("research did not progress")
        must("say", "Red science is automated: smelters -> belts -> gears -> flasks -> lab. Researching %s." % tech.get("current"))
        print("SCIENCE RUN PASS")


if __name__ == "__main__":
    try:
        main()
    except ChatInterrupt as e:
        print(f"INTERRUPTED: {e}")
        sys.exit(3)
    except PlayFail as e:
        print(f"FAIL: {e}", file=sys.stderr)
        sys.exit(1)
